services:
    discord-bot:
        build:
            context: ./
            dockerfile: ./discord-bot/Dockerfile
        network_mode: host
        restart: unless-stopped
        volumes:
            - /home/cuzkov/mc-servers-stats:/mc-server-statistics

    web-site:
        build:
            context: ./
            dockerfile: ./web-site/Dockerfile
        network_mode: host
        restart: unless-stopped
