version: '3.3'

services:
    discord-bot:
        build:
            context: ./
            dockerfile: ./discord-bot/Dockerfile
        network_mode: host

    web-site:
        build:
            context: ./
            dockerfile: ./web-site/Dockerfile
        network_mode: host
