version: '3.3'

services:
    discord-bot:
        build:
            context: ./
            dockerfile: ./discord-bot/Dockerfile
        network_mode: host
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s
        volumes:
            - /home/cuzkov/mc-servers-stats:/mc-server-statistics

    web-site:
        build:
            context: ./
            dockerfile: ./web-site/Dockerfile
        network_mode: host
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s
