version: '3.3'

services:
    server:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - /home/cuzkov/medieval-world:/usr/src/server/world
        ports:
            - 25565:25565