name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: "Deploy to yandex-cloud"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}


      - name: Fetching new version
        run: ssh server 'cd ./noelle && rm ./Noelle -R -f && git clone https://github.com/CUzkov/Noelle.git'
      
      - name: Copy secrets
        run: ssh server 'cp ./secrets/discord-bot/config.json ./noelle/Noelle/discord-bot/config.json && cp ./secrets/discord-bot/.ssh/minecraft-server ./noelle/Noelle/discord-bot/minecraft-server-key'

      - name: Rebuild discord-bot
        run: ssh server 'cd ./noelle/Noelle && sudo docker-compose build discord-bot'

      - name: Replace containers
        run: ssh server 'cd ./noelle/Noelle && sudo docker-compose up -d'

      - name: Clear unused images & containers
        run: ssh server 'cd ./noelle/Noelle && sudo docker system prune -f'

