name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: "Deploy to yandex-cloud"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/docs-hub.key
          chmod 600 ~/.ssh/docs-hub.key
          cat >>~/.ssh/config <<END
          Host docs-hub
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/docs-hub.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Fetching new version
        run: ssh docs-hub 'cd ./noelle && rm ./Noelle -R -f && git clone https://github.com/CUzkov/Noelle.git'
      
      - name: Copy secrets
        run: ssh docs-hub 'cd ./noelle && cp ./secrets/discord-bot/config.json ./Noelle/discord-bot/config.json'

      - name: Rebuild discord-bot
        run: ssh docs-hub 'cd ./noelle/Noelle && sudo docker-compose build discord-bot'

      - name: Replace containers
        run: ssh docs-hub 'cd ./noelle/Noelle && sudo docker-compose up -d'

      - name: Clear unused images & containers
        run: ssh docs-hub 'cd ./noelle/Noelle && sudo docker system prune -f'